PORTNAME=	hellodesktop
PORTVERSION=	
CATEGORIES=	x11-wm

MAINTAINER=	jsm@FreeBSD.org
COMMENT=	Meta-port for the helloDesktop
WWW=		https://github.com/helloSystem/hello

RUN_DEPENDS=	sysutils/hellodesktop-launch>=:sysutils/hellodesktop-launch \
		x11-wm/hellodesktop-menu>=:x11-wm/hellodesktop-menu \
		x11-fm/hellodesktop-filer>=:x11-fm/hellodesktop-filer \
		x11-themes/hellodesktop-icons>=:x11-themes/hellodesktop-icons \
		sysutils/hellodesktop-qtplugin>=:sysutils/hellodesktop-qtplugin \
		x11-themes/hellodesktop-breezeenhanced>=:x11-themes/hellodesktop-breezeenhanced \
		x11-fonts/hellodesktop-urwfonts-ttf>=:x11-fonts/hellodesktop-urwfonts-ttf
USES=		metaport

.include <bsd.port.mk>
