PORTNAME=	hellodesktop
PORTVERSION=	0.10.0
CATEGORIES=	x11-wm

MAINTAINER=	jsm@FreeBSD.org
COMMENT=	Meta-port for the helloDesktop
WWW=		https://github.com/helloSystem/hello

RUN_DEPENDS=	hellodesktop-launch>=0.10.0:sysutils/hellodesktop-launch \
	hellodesktop-menu>=0.10.0:x11-wm/hellodesktop-menu \
	x11-fm/hellodesktop-filer>=0.10.0:x11-fm/hellodesktop-filer \
	x11-themes/hellodesktop-icons>=0.10.0:x11-themes/hellodesktop-icons \
	sysutils/hellodesktop-qtplugin>=0.10.0:sysutils/hellodesktop-qtplugin \
	x11-themes/hellodesktop-breezeenhanced>=0.10.0:x11-themes/hellodesktop-breezeenhanced \
	x11-fonts/hellodesktop-urwfonts-ttf>=0.10.0:x11-fonts/hellodesktop-urwfonts-ttf
USES=	metaport

.include <bsd.port.mk>
