PORTNAME=	hellodesktop
PORTVERSION=	g20221111
CATEGORIES=	x11-wm

MAINTAINER=	jsm@FreeBSD.org
COMMENT=	Meta-port for the helloDesktop
WWW=		https://github.com/helloSystem/hello

RUN_DEPENDS=	sysutils/hellodesktop-launch>=0:sysutils/hellodesktop-launch \
		x11-wm/hellodesktop-menu>=0:x11-wm/hellodesktop-menu \
		x11-fm/hellodesktop-filer>=0:x11-fm/hellodesktop-filer \
		x11-themes/hellodesktop-icons>=0:x11-themes/hellodesktop-icons \
		sysutils/hellodesktop-qtplugin>=g20221109:sysutils/hellodesktop-qtplugin \
		x11-themes/hellodesktop-breezeenhanced>=0:x11-themes/hellodesktop-breezeenhanced \
		x11-fonts/hellodesktop-urwfonts-ttf>=g20200910:x11-fonts/hellodesktop-urwfonts-ttf
USES=		metaport

.include <bsd.port.mk>
